=== nurse/caster/lib/DTD/acc-template.dtd
<!--

	DTD for AjaxChatWrapper Template File

-->

<!ENTITY lt	"&#38;#60;">
<!ENTITY gt	"&#62;">
<!ENTITY amp	"&#38;#38;">
<!ENTITY apos	"&#39;">
<!ENTITY quot	"&#34;">

<!ENTITY % Forms	"(input | line-break | select | label )+" >
<!ENTITY % YesNo	"( yes | no )" >

<!ENTITY % InputType	"(string | integer | hidden | fixed | body | select)" >
<!ENTITY % pType	"( text | name | body | line | reload | mode | color | icon )" >

<!-- TOP LEVEL ELEMENT -->
<!ELEMENT template (options?,form,output?)>
<!ATTLIST template
	uri		CDATA		#REQUIRED
	system	CDATA		#REQUIRED
	>

<!-- CHAT OPTION -->
<!ELEMENT options (item)*>

<!ELEMENT item EMPTY>
<!ATTLIST item
	type	NMTOKEN	#REQUIRED
	value	CDATA	#IMPLIED
	>

<!-- FORM DEFINITION -->
<!ELEMENT form (fieldset)*>

<!-- FORM FIELD DEFINITIONS -->
<!ELEMENT fieldset %Forms;>
<!ATTLIST fieldset
	type	(main|option)	#REQUIRED
	>

<!-- FORM INPUT ELEMENT -->
<!ELEMENT input (#PCDATA)>
<!ATTLIST input
	type	%InputType;	#REQUIRED
	name	NMTOKEN		#REQUIRED
	saving	%YesNo;		#IMPLIED
	get		%YesNo;		#IMPLIED
	post	%YesNo;		#IMPLIED
	value	CDATA		#IMPLIED
	label	CDATA		#IMPLIED
	size	CDATA		#IMPLIED
	datasrc	NMTOKEN		#IMPLIED
	perceivedType
			%pType;		#IMPLIED
	>

<!-- FORM SELECTION ELEMENT -->
<!ELEMENT select (optgroup|option)*>
<!ATTLIST select
	type	NMTOKEN		#FIXED "select"
	name	NMTOKEN		#REQUIRED
	saving	%YesNo;		#IMPLIED
	get		%YesNo;		#IMPLIED
	post	%YesNo;		#IMPLIED
	label	CDATA		#REQUIRED
	src		CDATA		#IMPLIED
	title	CDATA		#IMPLIED
	perceivedType
			%pType;		#IMPLIED
	>

<!-- XHTML's optgoroup ELEMENT -->
<!ELEMENT optgoroup (option)*>
<!ATTLIST optgoroup
	label	CDATA		#REQUIRED
	title	CDATA		#IMPLIED
	>

<!-- XHTML's option ELEMENT -->
<!ELEMENT option (#PCDATA)>
<!ATTLIST option
	value	CDATA		#REQUIRED
	alt		CDATA		#IMPLIED
	title	CDATA		#IMPLIED
	>

<!-- Form line break -->
<!ELEMENT line-break EMPTY>

<!-- Form text label -->
<!ELEMENT label (#PCDATA)>

<!-- RESERVED FOR FUTURE USE -->
<!ELEMENT output EMPTY>

<!-- END OF DTD -->

=== nurse/caster/lib/templates/WindChat.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE template SYSTEM "../DTD/acc-template.dtd" >
<template uri="http://fuuka.org/WindChat" system="WindChat">
	<options />
	<form>
		<fieldset	type="main">
			<input	type="fixed"	perceivedType="text"	name="type" get="yes" post="yes" value="xml" />
			<input	type="fixed"	perceivedType="text"	name="version" get="yes" post="yes" value="0.4" />
			<input	type="string"	perceivedType="name"	name="name" saving="yes" get="yes" post="yes" value="" size="10" label="名前" />
			<input	type="string"	perceivedType="text"	name="status" saving="yes" get="yes" post="yes" value="" size="10" label="状態" />
			<input	type="integer"	perceivedType="line" name="line" saving="yes" get="yes" post="yes" value="50" size="2" label="行数" />
			<input	type="fixed"	perceivedType="mode"	name="mode"	post="yes" get="yes"	value="msg" />
			<line-break />
			<input	type="string"	perceivedType="body"	name="body" post="yes" value="" size="60" label="発言" />
		</fieldset>
		<fieldset type="option">
			<input	type="string"	perceivedType="color"	name="color" saving="yes" get="yes" post="yes" value="#343434" size="10" label="発言色" />
			<input	type="string"	perceivedType="uri"	name="uri" saving="yes" post="yes" value="" size="10" label="Site" />
			<input	type="string"	perceivedType="icon"	name="icon" saving="yes" post="yes" value="" size="10" label="アイコン" />
			<input	type="string"	perceivedType="text"	name="hash" saving="yes" get="yes" post="yes" value="" size="10" label="ID" />
			<input	type="string"	perceivedType="email"	name="email" saving="yes" post="yes" value="" size="10" label="E-Mail" />
			<input type="string"	perceivedType="text"	name="uri" saving="yes" post="yes" value="" size="10" label="Site" />
			<input	type="hidden"	perceivedType="reload"	name="retime" get="yes" post="yes" value="30" />
			<input	type="fixed"	perceivedType="text"	name="check" get="yes" post="yes" value="表" />
		</fieldset>
	</form>
	<output />
</template>

=== nurse/caster/lib/templates/Terra.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE template SYSTEM "../DTD/acc-template.dtd">
<template uri="http://wahah.jp/2005/Terra" system="Terra">
	<options>
		<item type="iconlist" value="?mode=iconlist" />
	</options>
	<form>
		<fieldset	type="main">
			<input	type="fixed"	perceivedType="text"	name="type"	get="yes"	post="yes"	value="xml"/>
			<input	type="fixed"	perceivedType="text"	name="version"	get="yes"	post="yes"	value="0.4" />
			<input	type="string"	perceivedType="name"	name="name"	saving="yes"	get="yes"	post="yes"	value=""	size="10"	label="名前"/>
			<input	type="string"	perceivedType="text"	name="status"	saving="yes"	get="yes"	post="yes"	value=""	size="10"	label="状態"/>
			<input	type="integer"	perceivedType="line"	name="line"	saving="yes"	get="yes"	post="yes"	value="20"	size="2"	label="行数"/>
			<input	type="fixed"	perceivedType="mode"	name="mode"	post="yes"	get="yes"	value="msg" />
<!--
			<select	type="select"	perceivedType="text"	name="rt"	saving="yes"	get="yes"	post="yes"	label="更新">
				<option	value="no">Active</option>
				<option	value="yes">Realtime</option>
			</select>
-->
			<line-break />
			<input	type="string"	perceivedType="body"	name="body"	post="yes"	size="60"	label="発言"/>
		</fieldset>
		<fieldset	type="option">
			<input	type="string"	perceivedType="color"	name="color"	saving="yes"	get="yes"	post="yes"	value="#888888"	size="10"	label="色"/>
			<input	type="string"	perceivedType="text"	name="publicid"	saving="yes"	get="yes"	post="yes"	value=""	size="10"	label="ID"	datasrc="name"/>
			<input	type="string"	perceivedType="email"	name="email" saving="yes" post="yes" value="" size="10" label="メッセ" />
			<input	type="string"	perceivedType="uri"	name="uri" saving="yes" post="yes" value="" size="10" label="mixi" />
			<input	type="string"	perceivedType="icon"	name="icon"	saving="yes"	get="yes"	post="yes"	value=""	size="10"	label="アイコン"/>
			<input	type="integer"	perceivedType="text"	name="icon_width"	saving="yes"	get="yes"	post="yes"	value=""	size="2"	label="幅"/>
			<input	type="integer"	perceivedType="text"	name="icon_height"	saving="yes"	get="yes"	post="yes"	value=""	size="2"	label="高さ"/>
			<input	type="hidden"	perceivedType="reload"	name="reload"	get="yes"	post="yes"	value="20" />
			<input	type="fixed"	perceivedType="text"	name="check"	get="yes"	post="yes"	value="表" />
		</fieldset>
	</form>
</template>

=== nurse/caster/lib/templates/Marldia.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE template SYSTEM "../DTD/acc-template.dtd" >
<template uri="http://airemix.com/Marldia" system="Marldia">
	<options>
		<item type="iconlist" value="?type=iconlist" />
	</options>
	<form>
		<fieldset type="main">
			<input type="fixed"		perceivedType="text"	name="type" get="yes" post="yes" value="xml" />
			<input type="fixed"		perceivedType="text"	name="version" get="yes" post="yes" value="0.4" />
			<input type="string"	perceivedType="name"	name="name" saving="yes" get="yes" post="yes" value="" size="10" label="名前" />
			<input type="integer"	perceivedType="line"	name="line" saving="yes" get="yes" post="yes" value="20" size="2" label="行数" />
			<line-break />
			<input type="string"	perceivedType="body"	name="body" post="yes" value="" size="60" label="発言" />
		</fieldset>
		<fieldset type="option">
			<input type="string"	perceivedType="text"	name="id" saving="yes" get="yes" post="yes" value="" size="10" label="Idendity" />
			<input type="string"	perceivedType="color"	name="color" saving="yes" get="yes" post="yes" value="#343434" size="10" label="名前色" />
			<input type="string"	perceivedType="color"	name="bcolo" saving="yes" post="yes" value="#343434" size="10" label="文章色" />
			<input type="string"	perceivedType="icon"	name="icon" saving="yes" post="yes" value="bwg/hellboy.png" size="10" label="アイコン" />
			<input type="string"	perceivedType="text"	name="opt" saving="yes" get="yes" post="yes" value="" size="10" label="Option" />
			<input type="string"	perceivedType="email"	name="email" saving="yes" post="yes" value="" size="10" label="E-mail" />
			<input type="string"	perceivedType="uri"		name="home" saving="yes" post="yes" value="" size="10" label="Home" />
			<input type="hidden"	perceivedType="reload"	name="reload" get="yes" post="yes" value="20" />
			<input type="fixed"		perceivedType="text"	name="encoding" get="yes" post="yes" value="utf-8" />
		</fieldset>
	</form>
	<output />
</template>
